CREATE TABLE IF NOT EXISTS ThanhVien81 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    taikhoan VARCHAR(255) NOT NULL Unique,
    matkhau VARCHAR(255) NOT NULL,
    ten VARCHAR(255) NOT NULL,
    diachi VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    dt INT(10) NOT NULL,
    ghichu VARCHAR(255) NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS NhanVien81 (
    ThanhVien81id INT(10) NOT NULL,
    vitri VARCHAR(255) NOT NULL,
    FOREIGN KEY (ThanhVien81id) REFERENCES ThanhVien81 (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS KhachHang81 (
    ThanhVien81id INT(10) NOT NULL,
    FOREIGN KEY (ThanhVien81id) REFERENCES ThanhVien81 (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Lichhen81 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    KhachHang81id INT(10) NOT NULL,
    ten VARCHAR(255) NOT NULL,
    dt VARCHAR(255) NOT NULL,
    thoigian TIMESTAMP NOT NULL,
    trangthai INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (KhachHang81id) REFERENCES ThanhVien81 (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS DichVu81 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    ten VARCHAR(255) NOT NULL,
    gia INT(30) NOT NULL,
    mota VARCHAR(255) NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PhuTung81 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    ten VARCHAR(255) NOT NULL,
    gia INT(30) NOT NULL,
    soluong INT(30) NOT NULL,
    mota VARCHAR(255) NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS HoaDon81 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    KhachHang81id INT(10) NOT NULL,
    NVBanHang81id INT(10) NOT NULL,
    thoigian TIMESTAMP NOT NULL,
    tongtien INT(30) NOT NULL,
    trangthai INT(10) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (KhachHang81id) REFERENCES ThanhVien81 (id) ON UPDATE CASCADE,
    FOREIGN KEY (NVBanHang81id) REFERENCES ThanhVien81 (id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PhuTungHoaDon81 (
    PhuTung81id INT(10) NOT NULL,
    HoaDon81id INT(10) NOT NULL,
    soluong INT(10) NOT NULL,
    gia INT(30) NOT NULL,
    PRIMARY KEY (PhuTung81id, HoaDon81id),
    FOREIGN KEY (PhuTung81id) REFERENCES PhuTung81 (id) ON UPDATE CASCADE,
    FOREIGN KEY (HoaDon81id) REFERENCES HoaDon81 (id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS DichVuHoaDon81 (
    DichVu81id INT(10) NOT NULL,
    HoaDon81id INT(10) NOT NULL,
    soluong INT(10) NOT NULL,
    gia INT(30) NOT NULL,
    PRIMARY KEY (DichVu81id, HoaDon81id),
    FOREIGN KEY (DichVu81id) REFERENCES DichVu81 (id) ON UPDATE CASCADE,
    FOREIGN KEY (HoaDon81id) REFERENCES HoaDon81 (id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS NVKithuatHoaDon81 (
    NVKiThuat81id INT(10) NOT NULL,
    HoaDon81id INT(10) NOT NULL,
    PRIMARY KEY (NVKiThuat81id, HoaDon81id),
    FOREIGN KEY (NVKiThuat81id) REFERENCES ThanhVien81 (id) ON UPDATE CASCADE,
    FOREIGN KEY (HoaDon81id) REFERENCES HoaDon81 (id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS NhaCungCap81 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    ten VARCHAR(255) NOT NULL,
    dt VARCHAR(255) NOT NULL,
    mota VARCHAR(255) NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS HoaDonNhap81 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    NhaCungCap81id INT(10) NOT NULL,
    thoigian TIMESTAMP NOT NULL,
    tongtien INT(30) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (NhaCungCap81id) REFERENCES NhaCungCap81 (id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PhuTungNhap81 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    ten VARCHAR(255) NOT NULL,
    gia INT(30) NOT NULL,
    soluong VARCHAR(255) NOT NULL,
    HoaDonNhap81id INT(10) NOT NULL,
    PhuTung81id INT(10) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (HoaDonNhap81id) REFERENCES HoaDonNhap81 (id) ON UPDATE CASCADE,
    FOREIGN KEY (PhuTung81id) REFERENCES PhuTung81 (id) ON UPDATE CASCADE
);
